# Generated by Django 4.2.9 on 2024-01-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('band', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='image')),
                ('uploded_at', models.DateTimeField(auto_now=True)),
                ('song_fle', models.FileField(upload_to='song')),
            ],
        ),
    ]
