# Generated by Django 4.2.9 on 2024-01-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_fle',
            new_name='song_file',
        ),
    ]
